# Parte 2 - Limpieza de datos

Revisamos y limpiamos los datos obtenidos mediante scraping.

In [8]:
import pandas as pd

df = pd.read_csv("datos/decretos_lluvias.csv")
df.head()

,numero,fecha,titulo,tipo,motivo,enlace
0,Decreto Supremo N.° 007-2025-PCM,10 de enero de 2025,Decreto Supremo que declara el Estado de Emerg...,declara,peligro inminente,https://www.gob.pe/institucion/pcm/normas-lega...
1,Decreto Supremo N.° 024-2025-PCM,26 de febrero de 2025,Decreto Supremo que declara el Estado de Emerg...,declara,impacto de daños,https://www.gob.pe/institucion/pcm/normas-lega...
2,Decreto Supremo N.° 021-2025-PCM,19 de febrero de 2025,Decreto Supremo que declara el Estado de Emerg...,declara,impacto de daños,https://www.gob.pe/institucion/pcm/normas-lega...
3,Decreto Supremo N.° 034-2025-PCM,12 de marzo de 2025,Decreto Supremo que declara el Estado de Emerg...,declara,impacto de daños,https://www.gob.pe/institucion/pcm/normas-lega...
4,Decreto Supremo N.° 033-2025-PCM,12 de marzo de 2025,Decreto Supremo que declara el Estado de Emerg...,declara,peligro inminente,https://www.gob.pe/institucion/pcm/normas-lega...

## Paso 1: Revisar los datos

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   numero  18 non-null     str
 1   fecha   18 non-null     str
 2   titulo  18 non-null     str
 3   tipo    18 non-null     str
 4   motivo  18 non-null     str
 5   enlace  18 non-null     str
dtypes: str(6)
memory usage: 9.1 KB

In [10]:
print("Duplicados:", df.duplicated().sum())

print("\nValores de tipo:")
print(df["tipo"].value_counts())

print("\nValores de motivo:")
print(df["motivo"].value_counts())

Duplicados: 0

Valores de tipo:
tipo
declara     11
prorroga     7
Name: count, dtype: int64

Valores de motivo:
motivo
impacto de daños     16
peligro inminente     2
Name: count, dtype: int64

## Paso 2: Limpiar los datos

In [11]:
# Convertir los meses a números
meses = {
    "enero": "01",
    "febrero": "02",
    "marzo": "03",
    "abril": "04",
    "mayo": "05",
    "junio": "06",
    "julio": "07",
    "agosto": "08",
    "septiembre": "09",
    "octubre": "10",
    "noviembre": "11",
    "diciembre": "12"
}

for mes, numero in meses.items():
    df["fecha"] = df["fecha"].str.replace(f" de {mes} de ", f"/{numero}/")

# Convertir la columna a fecha
df["fecha"] = pd.to_datetime(df["fecha"], format="%d/%m/%Y")

# Eliminar duplicados y valores nulos
df = df.drop_duplicates()
df = df.dropna()

df.head()

,numero,fecha,titulo,tipo,motivo,enlace
0,Decreto Supremo N.° 007-2025-PCM,2025-01-10,Decreto Supremo que declara el Estado de Emerg...,declara,peligro inminente,https://www.gob.pe/institucion/pcm/normas-lega...
1,Decreto Supremo N.° 024-2025-PCM,2025-02-26,Decreto Supremo que declara el Estado de Emerg...,declara,impacto de daños,https://www.gob.pe/institucion/pcm/normas-lega...
2,Decreto Supremo N.° 021-2025-PCM,2025-02-19,Decreto Supremo que declara el Estado de Emerg...,declara,impacto de daños,https://www.gob.pe/institucion/pcm/normas-lega...
3,Decreto Supremo N.° 034-2025-PCM,2025-03-12,Decreto Supremo que declara el Estado de Emerg...,declara,impacto de daños,https://www.gob.pe/institucion/pcm/normas-lega...
4,Decreto Supremo N.° 033-2025-PCM,2025-03-12,Decreto Supremo que declara el Estado de Emerg...,declara,peligro inminente,https://www.gob.pe/institucion/pcm/normas-lega...

## Paso 3: Verificar los datos limpios

In [12]:
df.info()

print("\nDuplicados:", df.duplicated().sum())
print("Valores nulos:")
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   numero  18 non-null     str
 1   fecha   18 non-null     datetime64[us]
 2   titulo  18 non-null     str
 3   tipo    18 non-null     str
 4   motivo  18 non-null     str
 5   enlace  18 non-null     str
dtypes: datetime64[us](1), str(5)
memory usage: 8.8 KB

Duplicados: 0
Valores nulos:
numero    0
fecha     0
titulo    0
tipo      0
motivo    0
enlace    0
dtype: int64

## Paso 4: Comparar antes y después

In [13]:
antes = pd.read_csv("datos/decretos_lluvias.csv")

comparacion = pd.DataFrame({
    "fecha_antes": antes["fecha"],
    "fecha_despues": df["fecha"]
})

comparacion.head()

             fecha_antes fecha_despues
0    10 de enero de 2025    2025-01-10
1  26 de febrero de 2025    2025-02-26
2  19 de febrero de 2025    2025-02-19
3    12 de marzo de 2025    2025-03-12
4    12 de marzo de 2025    2025-03-12

## Paso 5: Guardar los datos limpios

In [15]:
df.to_csv("datos/decretos_lluvias_limpio.csv", index=False)